name: my_portfolio_web_app
description: My Portfolio Web app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.1

dependencies:
  animated_theme_switcher: ^2.0.7
  bloc: ^8.1.1
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.2.0
  flutter_svg: ^2.0.1
  responsive_framework: ^0.2.0
  url_launcher: ^6.1.9
dependency_overrides:
  intl: 0.18.0

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/svg/
    - assets/images/
    - assets/images/social/
    - assets/images/projects/
    - assets/images/technology/
    # - outputs/gif/