name: my_portfolio_web_app
description: My Portfolio Web app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.1

dependencies:
  animated_theme_switcher: ^2.0.7
  bloc: ^8.1.1
  carousel_slider: ^4.2.1
  firebase_analytics: ^10.1.3
  firebase_core: ^2.6.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.1
  flutter_svg: ^2.0.1
  lottie: ^2.2.0
  responsive_framework: ^0.2.0
  url_launcher: ^6.1.9
dependency_overrides:
  intl: 0.18.0

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_launcher_icons: "^0.11.0"
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/me/
    - assets/svg/
    - assets/lottie/
    - assets/images/
    - assets/images/social/
    - assets/images/projects/
    - assets/images/technology/
    # - outputs/gif/
