// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0GpB5XGrCH0OqUznH3mZPa4TZEnNsvFg',
    appId: '1:320507244776:web:d2b817619035629a9e995d',
    messagingSenderId: '320507244776',
    projectId: 'wafiqmuhaz-web-fa8e0',
    authDomain: 'wafiqmuhaz-web-fa8e0.firebaseapp.com',
    storageBucket: 'wafiqmuhaz-web-fa8e0.appspot.com',
    measurementId: 'G-0TPH5BP6YL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrhzKnaKAuyoWGZCQaQnlEoskGnZgQgYg',
    appId: '1:320507244776:android:bfcc63fec80734bf9e995d',
    messagingSenderId: '320507244776',
    projectId: 'wafiqmuhaz-web-fa8e0',
    storageBucket: 'wafiqmuhaz-web-fa8e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwKdZ5YMG3HcFoKtg75cumluMcDzl55v4',
    appId: '1:320507244776:ios:1a51e1d83366dce19e995d',
    messagingSenderId: '320507244776',
    projectId: 'wafiqmuhaz-web-fa8e0',
    storageBucket: 'wafiqmuhaz-web-fa8e0.appspot.com',
    iosClientId: '320507244776-dqv2tn68skna9l0t2htfmcnrpvuhcs8f.apps.googleusercontent.com',
    iosBundleId: 'com.wafiqmuhaz.org.my-portfolio-web-app',
  );
}
